services:
  minio:
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      PORT: "9000"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      BUCKET_NAME: bucket
      MINIO_CONSOLE_PORT: "9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
